import argparse
import difflib
from pathlib import Path
from typing import List, Tuple


def _find_repo_root() -> Path:
    for candidate in Path(__file__).resolve().parents:
        if (candidate / "README.md").exists() and (candidate / ".github").exists():
            return candidate
    raise RuntimeError("Unable to determine repository root from script location.")


ROOT_DIR = _find_repo_root()
WORKFLOW_VALIDATION_DIR = ROOT_DIR / "workflow-validation"


TEXT_EXTENSIONS = {
    ".md",
    ".json",
    ".html",
    ".txt",
    ".yaml",
    ".yml",
    ".py",
}


def _list_files(root: Path) -> List[Path]:
    if not root.exists():
        return []
    return sorted([p for p in root.rglob("*") if p.is_file()])


def _relative_file_set(root: Path) -> set[str]:
    return {str(p.relative_to(root)).replace("\\", "/") for p in _list_files(root)}


def _read_text(path: Path) -> List[str]:
    return path.read_text(encoding="utf-8", errors="replace").splitlines()


def _is_text_file(path: Path) -> bool:
    return path.suffix.lower() in TEXT_EXTENSIONS


def compare_case(case_name: str) -> Tuple[str, str]:
    case_dir = WORKFLOW_VALIDATION_DIR / case_name
    expected = case_dir / "expected-outputs"
    generated = case_dir / "generated-outputs"

    if not expected.exists():
        raise ValueError(f"Missing expected outputs directory: {expected}")
    if not generated.exists():
        raise ValueError(f"Missing generated outputs directory: {generated}")

    expected_files = _relative_file_set(expected)
    generated_files = _relative_file_set(generated)

    missing = sorted(expected_files - generated_files)
    extra = sorted(generated_files - expected_files)
    shared = sorted(expected_files & generated_files)

    changed_text: List[str] = []
    changed_binary: List[str] = []

    for rel in shared:
        expected_path = expected / rel
        generated_path = generated / rel
        if _is_text_file(expected_path) and _is_text_file(generated_path):
            a = _read_text(expected_path)
            b = _read_text(generated_path)
            if a != b:
                diff_lines = list(
                    difflib.unified_diff(a, b, fromfile=f"expected/{rel}", tofile=f"generated/{rel}", n=1)
                )
                preview = "\n".join(diff_lines[:20])
                changed_text.append(f"- {rel}\n\n```diff\n{preview}\n```")
        else:
            if expected_path.read_bytes() != generated_path.read_bytes():
                changed_binary.append(rel)

    file_diff_lines: List[str] = []
    if missing:
        file_diff_lines.append("- Missing generated files compared to expected:")
        file_diff_lines.extend([f"  - {item}" for item in missing])
    if extra:
        file_diff_lines.append("- Extra generated files not present in expected:")
        file_diff_lines.extend([f"  - {item}" for item in extra])
    if changed_binary:
        file_diff_lines.append("- Binary files differ:")
        file_diff_lines.extend([f"  - {item}" for item in changed_binary])
    if changed_text:
        file_diff_lines.append("- Text files differ:")
        file_diff_lines.extend(changed_text)
    if not file_diff_lines:
        file_diff_lines.append("- No file differences detected.")

    qualitative = [
        "- Automated comparison completed. Review text diffs and structural differences above.",
        "- Confirm whether divergences reflect intentional workflow changes or regressions.",
    ]

    notable = []
    if missing:
        notable.append("- Generated output is missing files present in expected outputs.")
    if extra:
        notable.append("- Generated output contains additional files not present in expected outputs.")
    if changed_text or changed_binary:
        notable.append("- One or more shared files differ in content.")
    if not notable:
        notable.append("- No notable divergences found by automated file comparison.")

    block = [
        f"## Case: {case_name}",
        "### File differences (if any)",
        *file_diff_lines,
        "### Qualitative difference assessment",
        *qualitative,
        "### Noteable divergences",
        *notable,
        "",
    ]

    return case_name, "\n".join(block)


def init_report_text() -> str:
    return "\n".join(
        [
            "FILE IS GENERATED BY WORKFLOW VALIDATION - DO NOT EDIT MANUALLY",
            "",
            "# Workflow Validation Report",
            "",
        ]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare workflow validation generated outputs against expected outputs and write report blocks.",
    )
    parser.add_argument("--case", required=True, help="Validation case folder name.")
    parser.add_argument(
        "--report",
        type=Path,
        default=WORKFLOW_VALIDATION_DIR / "validation-report.md",
        help="Report file path.",
    )
    parser.add_argument(
        "--append",
        action="store_true",
        help="Append case section to report. If report does not exist, initialize first.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    _, block = compare_case(args.case)

    if args.append:
        if not args.report.exists():
            args.report.write_text(init_report_text(), encoding="utf-8")
        with args.report.open("a", encoding="utf-8") as handle:
            if args.report.stat().st_size > 0:
                handle.write("\n")
            handle.write(block)
        print(f"Appended report section for case: {args.case}")
        print(f"Report file: {args.report}")
    else:
        print(block)


if __name__ == "__main__":
    main()
